KEY = "card_id"
TARGET = "target"
INDIR = "../data/inputs/"
OUTDIR = "../data/outputs/"
TRNFEATDIR = "../data/features/trn/"
TSTFEATDIR = "../data/features/tst/"
SUMMARY = "../data/outputs/result_summary.csv"
